const fs = require('fs');

const dictionaries = {
  'zh': {
    'clearSearch': '清除搜索',
    'resultsFor': '结果：',
    'noMatchesFor': '没有匹配：',
    'order': '订单',
    'todayOffers': '今日特价',
    'hotDeals': '热门优惠',
    'from': '来自',
    'pickedForYou': '为您精选',
    'recommended': '推荐',
    'viewAll': '查看全部',
    'top': '顶级',
    'farmMenu': '农场菜单',
    'allGoodness': '所有美好',
    'noMatches': '没有找到匹配项',
    'tryDifferentSearch': '尝试不同的搜索词',
    'new': '新',
    'endOfGarden': '花园的尽头',
    'noOrdersYet': '暂无订单',
    'inProgress': '进行中',
    'ticket': '票',
    'rounding': '四舍五入',
    'archivedTickets': '已归档',
    'history': '历史',
    'endOfOrders': '订单结束',
    'viewCart': '查看购物车',
    'checkout': '结账',
    'yourCart': '您的购物车',
    'anyNotes': '有什么备注吗？',
    'perfectPairings': '完美搭配',
    'popularChoices': '热门选择',
    'searchMenu': '搜索菜单...',
    'farmToTable': '从农场到餐桌',
    'nature': '自然',
    'browseSub': '慢炖药膳汤搭配我们的招牌健康杂粮饭',
    'exploreMenu': '探索菜单',
    'thisWeek': '本周',
    'chefsFav': '主厨推荐',
    'popular': '受欢迎的',
    'add': '添加',
    'callStaff': '呼叫员工',
    'orders': '订单',
    'menu': '菜单',
    'home': '主页'
  },
  'ms': {
    'clearSearch': 'Kosongkan Carian',
    'resultsFor': 'Hasil untuk',
    'noMatchesFor': 'Tiada padanan untuk',
    'order': 'Pesanan',
    'todayOffers': 'Tawaran Hari Ini',
    'hotDeals': 'Tawaran Hebat',
    'from': 'dari',
    'pickedForYou': 'Pilihan Untuk Anda',
    'recommended': 'Disyorkan',
    'viewAll': 'Lihat Semua',
    'top': 'Atas',
    'farmMenu': 'Menu Ladang',
    'allGoodness': 'Semua Kebaikan',
    'noMatches': 'Tiada padanan ditemui',
    'tryDifferentSearch': 'Cuba istilah carian lain',
    'new': 'Baru',
    'endOfGarden': 'Hujung Taman',
    'noOrdersYet': 'Tiada pesanan lagi',
    'inProgress': 'Sedang Berjalan',
    'ticket': 'Tiket',
    'rounding': 'Penggenapan',
    'archivedTickets': 'Tiket Diarkibkan',
    'history': 'Sejarah',
    'endOfOrders': 'Tamat pesanan',
    'viewCart': 'Lihat Troli',
    'checkout': 'Selesai',
    'yourCart': 'Troli Anda',
    'anyNotes': 'Sebarang nota?',
    'perfectPairings': 'Gandingan Sempurna',
    'popularChoices': 'Pilihan Popular',
    'searchMenu': 'Cari menu...',
    'farmToTable': 'DARI LADANG KE MEJA',
    'nature': 'alam semula jadi',
    'browseSub': 'Sup herba direneh perlahan digandingkan dengan nasi pelbagai bijirin sihat kami',
    'exploreMenu': 'Teroka Menu',
    'thisWeek': 'MINGGU INI',
    'chefsFav': 'Kegemaran Chef',
    'popular': 'POPULAR',
    'add': 'Tambah',
    'callStaff': 'Panggil Staf',
    'orders': 'Pesanan',
    'menu': 'Menu',
    'home': 'Laman Utama'
  },
  'ar': {
    'clearSearch': 'مسح البحث',
    'resultsFor': 'نتائج لـ',
    'noMatchesFor': 'لا توجد تطابقات لـ',
    'order': 'طلب',
    'todayOffers': 'عروض اليوم',
    'hotDeals': 'عروض مميزة',
    'from': 'من',
    'pickedForYou': 'اخترنا لك',
    'recommended': 'موصى به',
    'viewAll': 'عرض الكل',
    'top': 'أعلى',
    'farmMenu': 'قائمة المزرعة',
    'allGoodness': 'كل الخيرات',
    'noMatches': 'لم يتم العثور على تطابقات',
    'tryDifferentSearch': 'جرب مصطلح بحث مختلف',
    'new': 'جديد',
    'endOfGarden': 'نهاية الحديقة',
    'noOrdersYet': 'لا توجد طلبات بعد',
    'inProgress': 'قيد التقدم',
    'ticket': 'تذكرة',
    'rounding': 'تقريب',
    'archivedTickets': 'التذاكر المؤرشفة',
    'history': 'سجل',
    'endOfOrders': 'نهاية الطلبات',
    'viewCart': 'عرض العربة',
    'checkout': 'الدفع',
    'yourCart': 'عربتك',
    'anyNotes': 'أي ملاحظات؟',
    'perfectPairings': 'أزواج مثالية',
    'popularChoices': 'خيارات شائعة',
    'searchMenu': 'ابحث في القائمة...',
    'farmToTable': 'من المزرعة إلى المائدة',
    'nature': 'الطبيعة',
    'browseSub': 'حساء الأعشاب المطبوخ ببطء مع الأرز الصحي متعدد الحبوب المميز لدينا',
    'exploreMenu': 'استكشف القائمة',
    'thisWeek': 'هذا الأسبوع',
    'chefsFav': 'مفضلات الشيف',
    'popular': 'شائع',
    'add': 'إضافة',
    'callStaff': 'نداء للموظفين',
    'orders': 'الطلبات',
    'menu': 'القائمة',
    'home': 'الرئيسية'
  },
  'fa': {
    'clearSearch': 'پاک کردن جستجو',
    'resultsFor': 'نتایج برای',
    'noMatchesFor': 'هیچ تطابقی برای',
    'order': 'سفارش',
    'todayOffers': 'پیشنهادات امروز',
    'hotDeals': 'تخفیف‌های ویژه',
    'from': 'از',
    'pickedForYou': 'انتخاب شده برای شما',
    'recommended': 'توصیه شده',
    'viewAll': 'مشاهده همه',
    'top': 'برتر',
    'farmMenu': 'منوی مزرعه',
    'allGoodness': 'همه خوبی‌ها',
    'noMatches': 'هیچ تطابقی یافت نشد',
    'tryDifferentSearch': 'عبارت جستجوی دیگری را امتحان کنید',
    'new': 'جدید',
    'endOfGarden': 'پایان باغ',
    'noOrdersYet': 'هنوز سفارشی نیست',
    'inProgress': 'در حال انجام',
    'ticket': 'بلیط',
    'rounding': 'گرد کردن',
    'archivedTickets': 'بلیط‌های بایگانی شده',
    'history': 'تاریخچه',
    'endOfOrders': 'پایان سفارشات',
    'viewCart': 'مشاهده سبد خرید',
    'checkout': 'پرداخت',
    'yourCart': 'سبد خرید شما',
    'anyNotes': 'یادداشتی دارید؟',
    'perfectPairings': 'ترکیب‌های عالی',
    'popularChoices': 'انتخاب‌های محبوب',
    'searchMenu': 'جستجو در منو...',
    'farmToTable': 'از مزرعه تا میز',
    'nature': 'طبیعت',
    'browseSub': 'سوپ گیاهی پخته شده با حرارت ملایم همراه با برنج چند غله سالم و مخصوص ما',
    'exploreMenu': 'کاوش در منو',
    'thisWeek': 'این هفته',
    'chefsFav': 'علاقه‌مندی‌های سرآشپز',
    'popular': 'محبوب',
    'add': 'افزودن',
    'callStaff': 'فراخوانی پرسنل',
    'orders': 'سفارشات',
    'menu': 'منو',
    'home': 'خانه'
  },
  'hi': {
    'clearSearch': 'खोज साफ़ करें',
    'resultsFor': 'के लिए परिणाम',
    'noMatchesFor': 'के लिए कोई मेल नहीं',
    'order': 'ऑर्डर',
    'todayOffers': 'आज के ऑफ़र',
    'hotDeals': 'गर्म सौदे',
    'from': 'से',
    'pickedForYou': 'आपके लिए चुना गया',
    'recommended': 'अनुशंसित',
    'viewAll': 'सभी देखें',
    'top': 'शीर्ष',
    'farmMenu': 'खेत मेनू',
    'allGoodness': 'सभी अच्छाई',
    'noMatches': 'कोई मेल नहीं मिला',
    'tryDifferentSearch': 'कोई अन्य खोज शब्द आज़माएं',
    'new': 'नया',
    'endOfGarden': 'बगीचे का अंत',
    'noOrdersYet': 'अभी तक कोई ऑर्डर नहीं',
    'inProgress': 'प्रगति पर',
    'ticket': 'टिकट',
    'rounding': 'गोलाकार करना',
    'archivedTickets': 'संग्रहीत टिकट',
    'history': 'इतिहास',
    'endOfOrders': 'ऑर्डर का अंत',
    'viewCart': 'कार्ट देखें',
    'checkout': 'चेकआउट',
    'yourCart': 'आपका कार्ट',
    'anyNotes': 'कोई नोट्स?',
    'perfectPairings': 'सही जोड़ियां',
    'popularChoices': 'लोकप्रिय विकल्प',
    'searchMenu': 'मेनू खोजें...',
    'farmToTable': 'खेत से मेज तक',
    'nature': 'प्रकृति',
    'browseSub': 'हमारे हस्ताक्षर स्वस्थ मल्टीग्रेन चावल के साथ धीमी गति से पका हुआ हर्बल सूप',
    'exploreMenu': 'मेनू का अन्वेषण करें',
    'thisWeek': 'इस सप्ताह',
    'chefsFav': 'शेफ की पसंद',
    'popular': 'लोकप्रिय',
    'add': 'जोड़ें',
    'callStaff': 'स्टाफ को बुलाएं',
    'orders': 'ऑर्डर',
    'menu': 'मेनू',
    'home': 'होम'
  }
};

const englishDefaults = {
  'clearSearch': 'Clear Search',
  'resultsFor': 'Results for',
  'noMatchesFor': 'No matches for',
  'order': 'Order',
  'todayOffers': "Today's Offers",
  'hotDeals': 'Hot Deals',
  'from': 'from',
  'pickedForYou': 'Picked For You',
  'recommended': 'Recommended',
  'viewAll': 'View All',
  'top': 'Top',
  'farmMenu': 'Farm Menu',
  'allGoodness': 'All the goodness',
  'noMatches': 'No matches found',
  'tryDifferentSearch': 'Try a different search term',
  'new': 'New',
  'endOfGarden': 'End of the garden',
  'noOrdersYet': 'No orders yet',
  'inProgress': 'In Progress',
  'ticket': 'Ticket',
  'rounding': 'Rounding',
  'archivedTickets': 'Archived Tickets',
  'history': 'History',
  'endOfOrders': 'End of orders',
  'viewCart': 'View Cart',
  'checkout': 'Checkout',
  'yourCart': 'Your Cart',
  'anyNotes': 'Any notes?',
  'perfectPairings': 'Perfect Pairings',
  'popularChoices': 'Popular Choices',
  'searchMenu': 'Search the menu...',
  'farmToTable': 'FARM TO TABLE',
  'nature': 'nature',
  'browseSub': 'Slow-simmered herbal soup paired with our signature healthy multigrain rice',
  'exploreMenu': 'Explore the Menu',
  'thisWeek': 'THIS WEEK',
  'chefsFav': "Chef's Favorites",
  'popular': 'POPULAR',
  'add': 'Add',
  'callStaff': 'Call Staff',
  'orders': 'Orders',
  'menu': 'Menu',
  'home': 'Home'
};

for (const [lang, dict] of Object.entries(dictionaries)) {
  const file = 'src/locales/' + lang + '.ts';
  let content = fs.readFileSync(file, 'utf8');
  
  for (const [key, translatedVal] of Object.entries(dict)) {
    const enVal = englishDefaults[key] || key;
    // We replace the english hardcoded string with the translation.
    // The keys look like: "customer.searchMenu": "Search the menu..."
    const regex = new RegExp('\"customer\\\\.' + key + '\":\\s*\"([^\"]+)\"', 'g');
    
    // Also try matching the exact key without regex if regex fails
    const target1 = '"customer.' + key + '": "' + enVal + '"';
    const target2 = '"customer.' + key + '": "' + key + '"';
    
    if (content.includes(target1)) {
      content = content.replace(target1, '"customer.' + key + '": "' + translatedVal + '"');
    } else if (content.includes(target2)) {
      content = content.replace(target2, '"customer.' + key + '": "' + translatedVal + '"');
    } else {
      // Use regex as fallback
      content = content.replace(regex, '"customer.' + key + '": "' + translatedVal + '"');
    }
  }
  
  fs.writeFileSync(file, content);
  console.log('Translated ' + lang);
}
