const fs = require('fs');

const keyMap = {
  "Employee Directory & Analytics": "m.empDir",
  "Add Employee": "m.addEmp",
  "Full Name": "m.fullName",
  "Department": "m.dept",
  "Employment Type": "m.empType",
  "Salary (RM)": "m.salary",
  "Save Employee": "m.saveEmp",
  "Staff Distribution": "m.staffDist",
  "Payroll Load by Department": "m.payrollLoad",
  "Edit": "m.edit",
  "Archive": "m.archive",
  "Inventory & Performance": "m.invPerf",
  "Overview Analytics": "m.overviewAnal",
  "Raw Stock Levels": "m.rawStock",
  "Menu Recipes Builder": "m.menuRecipes",
  "Inventory Health Status": "m.invHealth",
  "Menu Complexity": "m.menuComplexity",
  "Add Inventory Item": "m.addInvItem",
  "Current Stock": "m.currStock",
  "Save Item": "m.saveItem",
  "Edit Inventory Item": "m.editInvItem",
  "Audit Trail": "m.auditTrail",
  "Order & Revenue Events": "m.orderRev",
  "System & Inventory Events": "m.sysInv",
  "All Time": "m.allTime",
  "Last 24 Hours": "m.last24h",
  "Action": "m.action",
  "Actor": "m.actor",
  "Target": "m.target",
  "Menu Management": "m.menuMgmt",
  "Add Menu Item": "m.addMenuItem",
  "Price (RM) *": "m.price",
  "Category *": "m.category",
  "Description": "m.description",
  "Menu Image": "m.menuImage",
  "Mark as Popular": "m.markPopular",
  "Active Promotion": "m.activePromo",
  "Restaurant Working Hours": "m.restHours",
  "Opening Time": "m.openTime",
  "Closing Time": "m.closeTime",
  "Save Hours": "m.saveHours",
  "Manager Profile": "m.mgrProfile",
  "Manager ID": "m.mgrId",
  "Change Password": "m.changePass",
  "Save Profile": "m.saveProfile",
  "System Backup & Restore": "m.sysBackup",
  "Restaurant Tables": "m.restTables",
  "Add Table": "m.addTable",
  "Table Number/Name": "m.tableName",
  "QR Code Identifier": "m.qrId",
  "Save Table": "m.saveTable",
  "Financial Intelligence": "m.finInt",
  "Total Revenue": "m.totRev",
  "Gross Profit": "m.grossProf",
  "Net Earnings": "m.netEarn"
};

const enKeys = {};
for (const [k, v] of Object.entries(keyMap)) enKeys[v] = k;

const zhKeys = {
  "m.empDir": "员工名录和分析",
  "m.addEmp": "添加员工",
  "m.fullName": "全名",
  "m.dept": "部门",
  "m.empType": "雇佣类型",
  "m.salary": "工资 (RM)",
  "m.saveEmp": "保存员工",
  "m.staffDist": "员工分布",
  "m.payrollLoad": "各部门薪资负荷",
  "m.edit": "编辑",
  "m.archive": "存档",
  "m.invPerf": "库存和绩效",
  "m.overviewAnal": "概述分析",
  "m.rawStock": "原材料库存",
  "m.menuRecipes": "菜单配方生成器",
  "m.invHealth": "库存健康状态",
  "m.menuComplexity": "菜单复杂性",
  "m.addInvItem": "添加库存项目",
  "m.currStock": "当前库存",
  "m.saveItem": "保存项目",
  "m.editInvItem": "编辑库存项目",
  "m.auditTrail": "审计跟踪",
  "m.orderRev": "订单和收入事件",
  "m.sysInv": "系统和库存事件",
  "m.allTime": "所有时间",
  "m.last24h": "过去 24 小时",
  "m.action": "操作",
  "m.actor": "执行者",
  "m.target": "目标",
  "m.menuMgmt": "菜单管理",
  "m.addMenuItem": "添加菜单项目",
  "m.price": "价格 (RM) *",
  "m.category": "类别 *",
  "m.description": "描述",
  "m.menuImage": "菜单图片",
  "m.markPopular": "标记为热门",
  "m.activePromo": "促销活动",
  "m.restHours": "餐厅工作时间",
  "m.openTime": "开门时间",
  "m.closeTime": "关门时间",
  "m.saveHours": "保存时间",
  "m.mgrProfile": "经理资料",
  "m.mgrId": "经理 ID",
  "m.changePass": "更改密码",
  "m.saveProfile": "保存资料",
  "m.sysBackup": "系统备份和恢复",
  "m.restTables": "餐厅桌子",
  "m.addTable": "添加桌子",
  "m.tableName": "桌号/名称",
  "m.qrId": "二维码标识符",
  "m.saveTable": "保存桌子",
  "m.finInt": "财务智能",
  "m.totRev": "总收入",
  "m.grossProf": "毛利润",
  "m.netEarn": "净收益"
};

const msKeys = {
  "m.empDir": "Direktori Pekerja & Analitik",
  "m.addEmp": "Tambah Pekerja",
  "m.fullName": "Nama Penuh",
  "m.dept": "Jabatan",
  "m.empType": "Jenis Pekerjaan",
  "m.salary": "Gaji (RM)",
  "m.saveEmp": "Simpan Pekerja",
  "m.staffDist": "Pengagihan Staf",
  "m.payrollLoad": "Beban Gaji mengikut Jabatan",
  "m.edit": "Edit",
  "m.archive": "Arkib",
  "m.invPerf": "Inventori & Prestasi",
  "m.overviewAnal": "Analisis Gambaran Keseluruhan",
  "m.rawStock": "Tahap Stok Mentah",
  "m.menuRecipes": "Pembina Resipi Menu",
  "m.invHealth": "Status Kesihatan Inventori",
  "m.menuComplexity": "Kerumitan Menu",
  "m.addInvItem": "Tambah Item Inventori",
  "m.currStock": "Stok Semasa",
  "m.saveItem": "Simpan Item",
  "m.editInvItem": "Edit Item Inventori",
  "m.auditTrail": "Jejak Audit",
  "m.orderRev": "Acara Pesanan & Hasil",
  "m.sysInv": "Acara Sistem & Inventori",
  "m.allTime": "Sepanjang Masa",
  "m.last24h": "24 Jam Terakhir",
  "m.action": "Tindakan",
  "m.actor": "Pelakon",
  "m.target": "Sasaran",
  "m.menuMgmt": "Pengurusan Menu",
  "m.addMenuItem": "Tambah Item Menu",
  "m.price": "Harga (RM) *",
  "m.category": "Kategori *",
  "m.description": "Penerangan",
  "m.menuImage": "Imej Menu",
  "m.markPopular": "Tandai sebagai Popular",
  "m.activePromo": "Promosi Aktif",
  "m.restHours": "Waktu Bekerja Restoran",
  "m.openTime": "Waktu Buka",
  "m.closeTime": "Waktu Tutup",
  "m.saveHours": "Simpan Waktu",
  "m.mgrProfile": "Profil Pengurus",
  "m.mgrId": "ID Pengurus",
  "m.changePass": "Tukar Kata Laluan",
  "m.saveProfile": "Simpan Profil",
  "m.sysBackup": "Sandaran & Pemulihan Sistem",
  "m.restTables": "Meja Restoran",
  "m.addTable": "Tambah Meja",
  "m.tableName": "Nombor/Nama Meja",
  "m.qrId": "Pengecam Kod QR",
  "m.saveTable": "Simpan Meja",
  "m.finInt": "Perisikan Kewangan",
  "m.totRev": "Jumlah Hasil",
  "m.grossProf": "Untung Kasar",
  "m.netEarn": "Pendapatan Bersih"
};

const arKeys = {
  "m.empDir": "دليل الموظفين والتحليلات",
  "m.addEmp": "إضافة موظف",
  "m.fullName": "الاسم الكامل",
  "m.dept": "القسم",
  "m.empType": "نوع الوظيفة",
  "m.salary": "الراتب (RM)",
  "m.saveEmp": "حفظ الموظف",
  "m.staffDist": "توزيع الموظفين",
  "m.payrollLoad": "عبء الرواتب حسب القسم",
  "m.edit": "تعديل",
  "m.archive": "أرشيف",
  "m.invPerf": "المخزون والأداء",
  "m.overviewAnal": "نظرة عامة على التحليلات",
  "m.rawStock": "مستويات المخزون الخام",
  "m.menuRecipes": "منشئ وصفات القائمة",
  "m.invHealth": "حالة صحة المخزون",
  "m.menuComplexity": "تعقيد القائمة",
  "m.addInvItem": "إضافة عنصر مخزون",
  "m.currStock": "المخزون الحالي",
  "m.saveItem": "حفظ العنصر",
  "m.editInvItem": "تعديل عنصر المخزون",
  "m.auditTrail": "مسار التدقيق",
  "m.orderRev": "أحداث الطلبات والإيرادات",
  "m.sysInv": "أحداث النظام والمخزون",
  "m.allTime": "كل الوقت",
  "m.last24h": "آخر 24 ساعة",
  "m.action": "الإجراء",
  "m.actor": "الفاعل",
  "m.target": "الهدف",
  "m.menuMgmt": "إدارة القائمة",
  "m.addMenuItem": "إضافة عنصر قائمة",
  "m.price": "السعر (RM) *",
  "m.category": "الفئة *",
  "m.description": "الوصف",
  "m.menuImage": "صورة القائمة",
  "m.markPopular": "تعيين كشائع",
  "m.activePromo": "عرض ترويجي نشط",
  "m.restHours": "ساعات عمل المطعم",
  "m.openTime": "وقت الفتح",
  "m.closeTime": "وقت الإغلاق",
  "m.saveHours": "حفظ الساعات",
  "m.mgrProfile": "الملف الشخصي للمدير",
  "m.mgrId": "معرف المدير",
  "m.changePass": "تغيير كلمة المرور",
  "m.saveProfile": "حفظ الملف الشخصي",
  "m.sysBackup": "نسخ احتياطي واستعادة النظام",
  "m.restTables": "طاولات المطعم",
  "m.addTable": "إضافة طاولة",
  "m.tableName": "رقم/اسم الطاولة",
  "m.qrId": "معرف رمز الاستجابة السريعة",
  "m.saveTable": "حفظ الطاولة",
  "m.finInt": "الذكاء المالي",
  "m.totRev": "إجمالي الإيرادات",
  "m.grossProf": "إجمالي الربح",
  "m.netEarn": "صافي الأرباح"
};

const faKeys = {
  "m.empDir": "لیست کارمندان و تحلیل‌ها",
  "m.addEmp": "افزودن کارمند",
  "m.fullName": "نام کامل",
  "m.dept": "بخش",
  "m.empType": "نوع استخدام",
  "m.salary": "حقوق (RM)",
  "m.saveEmp": "ذخیره کارمند",
  "m.staffDist": "توزیع کارکنان",
  "m.payrollLoad": "بار حقوق بر اساس بخش",
  "m.edit": "ویرایش",
  "m.archive": "بایگانی",
  "m.invPerf": "انبار و عملکرد",
  "m.overviewAnal": "تحلیل کلی",
  "m.rawStock": "سطح موجودی خام",
  "m.menuRecipes": "سازنده دستور العمل منو",
  "m.invHealth": "وضعیت سلامت انبار",
  "m.menuComplexity": "پیچیدگی منو",
  "m.addInvItem": "افزودن کالای انبار",
  "m.currStock": "موجودی فعلی",
  "m.saveItem": "ذخیره کالا",
  "m.editInvItem": "ویرایش کالای انبار",
  "m.auditTrail": "ردیابی ممیزی",
  "m.orderRev": "رویدادهای سفارش و درآمد",
  "m.sysInv": "رویدادهای سیستم و انبار",
  "m.allTime": "تمام زمان‌ها",
  "m.last24h": "24 ساعت گذشته",
  "m.action": "عملیات",
  "m.actor": "انجام دهنده",
  "m.target": "هدف",
  "m.menuMgmt": "مدیریت منو",
  "m.addMenuItem": "افزودن مورد منو",
  "m.price": "قیمت (RM) *",
  "m.category": "دسته بندی *",
  "m.description": "توضیحات",
  "m.menuImage": "تصویر منو",
  "m.markPopular": "نشان‌گذاری به عنوان محبوب",
  "m.activePromo": "تبلیغ فعال",
  "m.restHours": "ساعات کاری رستوران",
  "m.openTime": "زمان باز شدن",
  "m.closeTime": "زمان بسته شدن",
  "m.saveHours": "ذخیره ساعات",
  "m.mgrProfile": "نمایه مدیر",
  "m.mgrId": "شناسه مدیر",
  "m.changePass": "تغییر رمز عبور",
  "m.saveProfile": "ذخیره نمایه",
  "m.sysBackup": "پشتیبان‌گیری و بازیابی سیستم",
  "m.restTables": "میزهای رستوران",
  "m.addTable": "افزودن میز",
  "m.tableName": "شماره/نام میز",
  "m.qrId": "شناسه کد QR",
  "m.saveTable": "ذخیره میز",
  "m.finInt": "هوش مالی",
  "m.totRev": "کل درآمد",
  "m.grossProf": "سود ناخالص",
  "m.netEarn": "درآمد خالص"
};

const hiKeys = {
  "m.empDir": "कर्मचारी निर्देशिका और विश्लेषिकी",
  "m.addEmp": "कर्मचारी जोड़ें",
  "m.fullName": "पूरा नाम",
  "m.dept": "विभाग",
  "m.empType": "रोजगार का प्रकार",
  "m.salary": "वेतन (RM)",
  "m.saveEmp": "कर्मचारी सहेजें",
  "m.staffDist": "स्टाफ वितरण",
  "m.payrollLoad": "विभाग द्वारा पेरोल लोड",
  "m.edit": "संपादित करें",
  "m.archive": "पुरालेख",
  "m.invPerf": "इन्वेंटरी और प्रदर्शन",
  "m.overviewAnal": "अवलोकन विश्लेषिकी",
  "m.rawStock": "कच्चे स्टॉक का स्तर",
  "m.menuRecipes": "मेनू पकाने की विधि निर्माता",
  "m.invHealth": "इन्वेंटरी स्वास्थ्य स्थिति",
  "m.menuComplexity": "मेनू जटिलता",
  "m.addInvItem": "इन्वेंटरी आइटम जोड़ें",
  "m.currStock": "वर्तमान स्टॉक",
  "m.saveItem": "आइटम सहेजें",
  "m.editInvItem": "इन्वेंटरी आइटम संपादित करें",
  "m.auditTrail": "ऑडिट ट्रेल",
  "m.orderRev": "आदेश और राजस्व घटनाएँ",
  "m.sysInv": "सिस्टम और इन्वेंटरी घटनाएँ",
  "m.allTime": "हर समय",
  "m.last24h": "पिछले 24 घंटे",
  "m.action": "कार्रवाई",
  "m.actor": "अभिनेता",
  "m.target": "लक्ष्य",
  "m.menuMgmt": "मेनू प्रबंधन",
  "m.addMenuItem": "मेनू आइटम जोड़ें",
  "m.price": "मूल्य (RM) *",
  "m.category": "श्रेणी *",
  "m.description": "विवरण",
  "m.menuImage": "मेनू छवि",
  "m.markPopular": "लोकप्रिय के रूप में चिह्नित करें",
  "m.activePromo": "सक्रिय प्रचार",
  "m.restHours": "रेस्तरां के काम के घंटे",
  "m.openTime": "खुलने का समय",
  "m.closeTime": "बंद होने का समय",
  "m.saveHours": "घंटे सहेजें",
  "m.mgrProfile": "प्रबंधक प्रोफ़ाइल",
  "m.mgrId": "प्रबंधक आईडी",
  "m.changePass": "पासवर्ड बदलें",
  "m.saveProfile": "प्रोफ़ाइल सहेजें",
  "m.sysBackup": "सिस्टम बैकअप और रिस्टोर",
  "m.restTables": "रेस्तरां टेबल",
  "m.addTable": "टेबल जोड़ें",
  "m.tableName": "टेबल संख्या/नाम",
  "m.qrId": "क्यूआर कोड पहचानकर्ता",
  "m.saveTable": "टेबल सहेजें",
  "m.finInt": "वित्तीय बुद्धिमत्ता",
  "m.totRev": "कुल राजस्व",
  "m.grossProf": "सकल लाभ",
  "m.netEarn": "शुद्ध आय"
};

function injectKeys(filePath, keys) {
  let content = fs.readFileSync(filePath, 'utf8');
  let newKeysStr = Object.entries(keys).map(([k, v]) => `    "${k}": "${v}"`).join(',\n');
  content = content.replace(/  \}\n\};\n?$/, `,\n${newKeysStr}\n  }\n};\n`);
  fs.writeFileSync(filePath, content);
}

injectKeys('src/locales/en.ts', enKeys);
injectKeys('src/locales/zh.ts', zhKeys);
injectKeys('src/locales/ms.ts', msKeys);
injectKeys('src/locales/ar.ts', arKeys);
injectKeys('src/locales/fa.ts', faKeys);
injectKeys('src/locales/hi.ts', hiKeys);

const files = [
  'src/components/garden/management/EmployeesTab.tsx',
  'src/components/garden/management/FinanceTab.tsx',
  'src/components/garden/management/InventoryTab.tsx',
  'src/components/garden/management/LogsTab.tsx',
  'src/components/garden/management/MenuTab.tsx',
  'src/components/garden/management/SettingsTab.tsx',
  'src/components/garden/management/TablesTab.tsx'
];

for (const file of files) {
  let code = fs.readFileSync(file, 'utf8');
  for (const [k, v] of Object.entries(keyMap)) {
    // Only replace outside tags or in basic places
    // Safe replace: ">Original String<" -> ">{t('key')}<"
    const regex = new RegExp('>' + k.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '<', 'g');
    code = code.replace(regex, '>{t("' + v + '")}<');
  }
  if (!code.includes('useTranslation')) {
    code = code.replace('import { useState', 'import { useTranslation } from "react-i18next";\nimport { useState');
    // Find the export function component and inject useTranslation hook
    code = code.replace(/export function (\w+)\(([^)]*)\) \{/, 'export function $1($2) {\n  const { t } = useTranslation();');
  }
  fs.writeFileSync(file, code);
}
console.log("Management Tabs translated!");
